name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  instrumentation-tests:
    name: Instrumentation tests
    strategy:
      matrix:
        api-level: [ 23, 26, 28 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - run: chmod +x gradlew
      - uses: gradle/gradle-build-action@v2
      - run: docker-compose -f docker/docker-compose-ci.yml up --build -d
      - uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-x86_64-8192m
      - if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          sdcard-path-or-size: 1000M
          ram-size: 8192M
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          ram-size: 8192M
          sdcard-path-or-size: 1000M
          disable-animations: true
          script: |
            adb logcat *:E &
            adb shell pm list packages | grep dev.yorkie.test && adb uninstall dev.yorkie.test || true;
            ./gradlew yorkie:createDebugAndroidTestCoverageReport --info
      - uses: actions/upload-artifact@v3
        with:
          name: android-test-artifact
          path: yorkie/build/reports/coverage/androidTest/debug/connected/report.xml

  microbenchmarks:
    name: Microbenchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - run: chmod +x gradlew
      - uses: gradle/gradle-build-action@v2
      - uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-28-x86_64-8192m
      - if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          ram-size: 8192M
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          ram-size: 8192M
          disable-animations: true
          script: |
            adb logcat *:E &
            ./gradlew microbenchmark:assembleReleaseAndroidTest;
            adb shell pm list packages | grep dev.yorkie.microbenchmark.test && adb uninstall dev.yorkie.microbenchmark.test || true;
            adb install microbenchmark/build/outputs/apk/androidTest/release/microbenchmark-release-androidTest.apk;
            adb shell am instrument -w -e no-isolated-storage true -e additionalTestOutputDir /sdcard/Download/ -e "androidx.benchmark.suppressErrors" "EMULATOR,LOW-BATTERY,UNLOCKED" dev.yorkie.microbenchmark.test/androidx.benchmark.junit4.AndroidBenchmarkRunner;
            adb shell find /sdcard/Download -name "*-benchmarkData.json" | tr -d '\r' | xargs -n1 adb pull
      - run: |
          echo "$(cat dev.yorkie.microbenchmark.test-benchmarkData.json)"
      - uses: actions/upload-artifact@v3
        with:
          name: microbenchmark-artifact
          path: dev.yorkie.microbenchmark.test-benchmarkData.json
