name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - run: chmod +x gradlew
      - uses: gradle/gradle-build-action@v2
      - run: ./gradlew lintKotlin
      - run: ./gradlew lint

  instrumentation-tests:
    name: Instrumentation tests
    strategy:
      matrix:
        api-level: [ 23, 26, 28 ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - run: chmod +x gradlew
      - uses: gradle/gradle-build-action@v2
      - run: docker-compose -f docker/docker-compose-ci.yml up --build -d
      - uses: actions/cache@v3
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}-x86_64-8192m
      - if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          ram-size: 8192M
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."
      - uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          ram-size: 8192M
          disable-animations: true
          script: |
            adb shell pm list packages | grep dev.yorkie.test && adb uninstall dev.yorkie.test || true;
            ./gradlew yorkie:createDebugAndroidTestCoverageReport
      - uses: actions/upload-artifact@v3
        with:
          name: android-test-artifact
          path: yorkie/build/reports/coverage/androidTest/debug/connected/report.xml
